" Don't try to be vi compatible
set nocompatible


" disable swapfiles (they are a nuisance)
set noswapfile
" Helps force plugins to load correctly when it is turned back on below
filetype off

" TODO: Load plugins here (pathogen or vundle)

" mouse mode

"if has('mouse')
"  set mouse=a
"  set selectmode=cmd
"endif


" Turn on syntax highlighting
syntax on
" For plugins to load correctly
filetype plugin indent on

" TODO: Pick a leader key
" let mapleader = ","


" Show line numbers
set number

" Show file stats
set ruler

" Encoding
set encoding=utf-8

" Cursor motion
set scrolloff=0
set matchpairs+=<:> " use % to jump between pairs
runtime! macros/matchit.vim

" Move up/down editor lines
nnoremap k gj
nnoremap j gk


" Rendering
set ttyfast

" Last line
set showcmd

" Searching
nnoremap / /\v
vnoremap / /\v
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
map <leader><space> :let @/=''<cr> " clear search

" Visualize tabs and newlines
set listchars=tab:▸\ ,eol:¬
" Uncomment this to enable by default:
" set list " To enable by default
" Or use your leader key + l to toggle on/off
map <leader>l :set list!<CR> " Toggle tabs and EOL


" use 4 spaces instead of tabs
set tabstop=2
